[package]
name = "reverse_seq-5a00e05cc374cb34d100000d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
