[package]
name = "abbrev_name-57eadb7ecd143f4c9c0000a3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
